# Generated by Django 3.2 on 2024-11-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hce', '0003_patient_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='testretult',
            new_name='testresult',
        ),
        migrations.AlterField(
            model_name='patient',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='correo',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='documento',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='documento',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='test',
            name='testname',
            field=models.CharField(max_length=100),
        ),
    ]
