# Generated by Django 3.2 on 2024-11-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hce', '0005_remove_patient_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100, unique=True)),
                ('area', models.CharField(choices=[('Biomédica', 'Biomédica'), ('Infraestructura', 'Infraestructura'), ('Sistemas', 'Sistemas')], max_length=100)),
                ('responsable', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
            ],
        ),
    ]
